FROM golang

#RUN go mod init github.com/golangbot/mysqltutorial

RUN go get -u github.com/go-sql-driver/mysql

RUN go get github.com/manohar-gitRepo/golangAPIExample

WORKDIR /golangAPIExample

#copy files
COPY api.go /golangAPIExample

#gooo build
RUN go build /golangAPIExample/api.go

EXPOSE 8000

# run the binary
CMD ["/golangAPIExample/api"]
