FROM golang

#RUN go mod init github.com/golangbot/mysqltutorial

RUN go get -u github.com/go-sql-driver/mysql

RUN go get github.com/manohar-gitRepo/golangAPIExample

WORKDIR /go/src/app

#copy files
RUN cp  /api.go /go/src/app

#gooo build
RUN go build /go/src/app/api.go

EXPOSE 8000

# run the binary
CMD ["/go/src/app/api"]
